# Example configuration properties
app.datasource.url=mysql+aiomysql://root:1234qwer@localhost:3306/webapp
security.content.key=SECURITY_CONTEXT_KEY
security.jwt.enable=true
http.multipart.enabled=true
http.multipart.max-file-size=50MB
http.multipart.max-request-size=50MB
security.jwt.enable=true
verification.token.header.name=X-CSRFToken
app.name=accountslogin
filter.sql.enable=true
context.path=/accountslogin


app.resources.chroma=resources/chroma
app.resources.data.books=resources/data/books
app.resources.static.uploads.pdfs=resources/static/uploads/pdfs
app.resources.static.downloads.mds=resources/static/downloads/mds



